version: "3"

x-app_environment: &app_environment
  restart: unless-stopped
  env_file:
    - .env

services:
  database:
    image: mysql:8
    volumes:
      - database_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/*
    ports:
      - "3306:3306"
    <<: *app_environment
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app:cached
    entrypoint: ./wait-for-it.sh database:3306 -- ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    <<: *app_environment

volumes:
  database_data:
