version: "2"

services:
  database:
    image: mysql:8
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app:cached
    entrypoint: ./wait-for-it.sh database:3306 -- ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env

volumes:
  database_data:
