on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: 51.250.17.135
          username: avidyakov
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "~/pdd_hint"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.17.135
          username: avidyakov
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: 22
          script: cd pdd_hint && docker-compose up --build -d
